// /sources 表示用の日本語ラベル。facts.json のキー → 人が読む名称
export const JA_LABELS: Record<string, string> = {
  // facts
  workWeekHours: '週勤務時間',
  dailyHours: '1日の勤務時間',
  workHoursSpan: '勤務時間帯',
  restBreak: '休憩',
  chiikiTeateIryou: '地域手当（医療職の支給率）',
  overtimeWeekday: '時間外（勤務日）の割増率',
  overtimeOffday: '時間外（週休日等）の割増率',
  salaryTerms: '給料以外の手当の種類',
  bonusKimatsuRate: '期末手当（月数）',
  bonusKinbenRate: '勤勉手当（月数・総額上限）',
  yakushokuKasan: '期末・勤勉手当の役職加算',
  yakushokuKasanTiers: '役職加算の級別割合（別表第2）',
  bonusYakushokuKasan: '期末・勤勉手当の役職加算（級別割合）',
  raiseStopAge: '昇給停止年齢',
  kanrishokuCap: '管理職手当の上限率',
  jukyoBase: '住居手当の対象となる家賃の下限',
  bonusKinbenRateOther: '勤勉手当（再任用・任期付等の区分）',
  bonusKinbenSeisekiritsu: '勤勉手当の成績率の仕組み',
  annualBonusMonths: '年間賞与月数',
  bonusBase: '期末・勤勉手当の基礎額',
  chiikiTeatePercent: '地域手当（支給率）',
  chiikiTeateBase: '地域手当の基礎額',
  fuyoSpouse: '扶養手当（配偶者）',
  fuyoSpouseNote: '扶養手当（配偶者・補足）',
  fuyo7kyuNote: '扶養手当（7級の父母等特例）',
  fuyoChild: '扶養手当（子）',
  fuyoChildAdd16to22: '扶養手当（16〜22歳の子の加算）',
  fuyoParents: '扶養手当（父母等）',
  jukyoFormula: '住居手当（計算方法）',
  jukyoMax: '住居手当（上限額）',
  tsukinVehicle: '通勤手当（自動車・バイク・自転車）',
  tsukinTransit: '通勤手当（電車・バス）',
  kanrishokuTeate: '管理職手当',
  overtimeRates: '時間外勤務の割増率',
  overtimeHoliday: '休日勤務の割増率',
  overtimeOver60h: '時間外（月60時間超）の割増率',
  overtimeNight: '夜間勤務の割増率',
  hourlyRateFormula: '勤務1時間当たりの給与額（計算式）',
  raiseSteps: '昇給の号給数',
  raiseCap: '昇給の上限',
  raiseDate: '昇給日',
  tandokuFunin: '単身赴任手当',
  tandokuFuninDistanceAdd: '単身赴任手当（距離加算）',
  kanriTokubetsuKinmuTeate: '管理職員特別勤務手当',
  kanriTokubetsuKinmuMax: '管理職員特別勤務手当（上限額）',
  kanrishokuTeateCap: '管理職手当の上限',
  overtimeCap: '時間外勤務の上限時間',
  overtimeCapChildcare: '時間外勤務の上限（育児・介護中）',
  shukuNichoku: '宿日直手当',
  senior7wari: '60歳に達した職員の給料特例（7割）',
  senior7wariExclusion: '60歳特例の適用除外',
  kyuryoTable: '給料表の構成',
  salaryTransitionGuarantee: '給料表切替時の現給保障（経過措置）',
  // leave
  types: '休暇の種類',
  annualLeaveDays: '年次有給休暇の日数',
  annualLeaveBasis: '年休の起算（年度・暦年）',
  annualLeaveCarryOver: '年休の繰越し',
  midYearHire: '年途中採用の年休付与日数',
  specialLeave: '特別休暇',
  specialLeaveNote: '特別休暇（補足）',
  mourning: '忌引',
  mourningNote: '忌引（補足）',
  sickLeave: '療養休暇',
  careLeave: '介護休暇',
  careLeaveUnpaid: '介護休暇・介護時間・組合休暇（有給・無給）',
  careTime: '介護時間',
  kumiaiLeave: '組合休暇',
  // kaikei
  structureNote: '会計年度任用職員の構成',
  salaryTable: '会計年度の給料表・勤務時間',
  salaryTableRef: '会計年度の給料表',
  chiikiTeate: '地域手当（会計年度）',
  bonusKimatsu: '期末手当（会計年度）',
  bonusKinben: '勤勉手当（会計年度）',
  annualLeaveNew: '年次有給休暇（新規任用）',
  annualLeaveContinuing: '年次有給休暇（継続任用）',
  shoninGokyu: '会計年度の初任給号給',
  raise: '会計年度の昇給',
  hoshuFormula: '会計年度の月額報酬の算定式',
  bonus: '期末・勤勉手当（月数）',
  kekkon: '結婚休暇（会計年度）',
  kaki: '夏季休暇（会計年度）',
  sanzenSango: '産前産後休暇（会計年度）',
  unpaidPaidSplit: '有給・無給の区分（会計年度）',
  eligibilityCondition: '特別休暇の対象条件（会計年度）',
  baseAmount: '基準月額・報酬の算定',
  maxAge: '任用の上限年齢',
  commute: '通勤費用弁償',
  commuteFulltime: '通勤費（フルタイム）',
  bonusRate: '期末・勤勉手当（月数）',
  bonusEligibilityThreshold: '期末・勤勉手当の対象条件',
  annualLeave: '年次有給休暇',
  annualLeaveMidYear: '年度途中任用の年休',
  leaveTypes: '休暇の種類（会計年度）',
  kakiKyuka: '夏季休暇',
  unpaidLeave: '無給の休暇・休業',
  covidLeave: '新型コロナ入院時の特例',
  // notFound キー（key.split('.').pop() で参照される表示名）
  'tsukinVehicle/tsukinTransit': '通勤手当の距離別実額表（例規集に規定なし・手帳別冊で反映済み）',
  'specialWorkAllowance(特殊勤務手当実額)': '特殊勤務手当（実額）',
  'retirementAllowance(退職手当)': '退職手当',
  'sickLeave固定日数（正職員）': '病気休暇の固定日数（正職員）',
  tsukinVehicleFullTable: '自動車等通勤手当（全距離帯の実額表）',
  特殊勤務手当実額: '特殊勤務手当（実額）',
  退職手当: '退職手当',
  夏季休暇: '夏季特別休暇',
  フルタイム会計年度給料表: 'フルタイム会計年度任用職員の給料表',
  医療職給料表: '医療職給料表',
  '初任給基準・昇格基準の実表': '初任給・昇格・格付の基準表',
};

export function jaLabel(key: string): string {
  return JA_LABELS[key] ?? key;
}

// ネストしたオブジェクト値の内部キー → 日本語（/sources の生JSON表示を無くす）
export const NESTED_LABELS: Record<string, string> = {
  jun: '6月期',
  dec: '12月期',
  kimatsu: '期末手当',
  kinben: '勤勉手当',
  weekday: '平日',
  offday: '週休日等',
  holiday: '休日',
  over60h: '月60時間超',
  midnightAdd: '深夜加算',
  night: '夜間',
  normal: '通常',
  over55: '55歳超',
  stopOver: '60歳超（昇給停止）',
  cap: '上限',
  poorPerformance: '勤務成績不良',
  // 会計年度の入れ子キー
  fulltime: 'フルタイム',
  parttime_upper: 'パートタイム上限',
  parttime_daily_upper: 'パートタイム1日上限',
  weekly5plus: '週5日以上',
  weekly4: '週4日',
  weekly3: '週3日',
  unit: '取得単位',
  note: '備考',
  paid: '有給',
  unpaid: '無給',
  period: '期間',
  max: '最大日数',
  byRole: '職種別',
  before: '産前',
  after: '産後',
};

export function nestedLabel(key: string): string {
  return NESTED_LABELS[key] ?? key;
}
